"use client";
import Image from "next/image";
import {motion,useScroll,useTransform} from "motion/react";
import {ArrowUpRight,ArrowDown,Github,Linkedin,Mail,Sparkles} from "lucide-react";
import StudioNav from "./StudioNav";
import project1 from "../src/assets/project1.png";import project3 from "../src/assets/project3.jpg";import project4 from "../src/assets/project4.png";import project6 from "../src/assets/project6.png";import profile from "../src/assets/profile.png";
const projects=[
 {number:"01",title:"Fintrack",category:"Product",year:"2026",description:"A focused personal-finance experience for tracking spending, savings, and day-to-day decisions.",image:project1,href:"/work/fintrack",stack:["Next.js","TypeScript","Prisma"]},
 {number:"02",title:"Cyber Crew",category:"Community",year:"2025",description:"A cybersecurity community experience for events, learning, and collaborative building.",image:project6,href:"/work/cyber-crew",stack:["React","Tailwind","UI"]},
 {number:"03",title:"Wireless Campus",category:"Systems",year:"2024",description:"A campus networking project covering infrastructure, topology, and practical connectivity.",image:project3,href:"/work/wireless-campus",stack:["CCNA","Cisco","Networking"]},
 {number:"04",title:"File Transfer Tool",category:"Tool",year:"2025",description:"A focused Python networking utility for controlled file sharing across endpoints.",image:project4,href:"/work/file-transfer",stack:["Python","Sockets","Networking"]}
];
export default function PortfolioHome(){const{scrollYProgress}=useScroll();const heroY=useTransform(scrollYProgress,[0,.2],[0,-36]);const heroScale=useTransform(scrollYProgress,[0,.2],[1,.96]);return <main>
<StudioNav/>
<section className="hero"><div className="hero-bg" aria-hidden="true"><div className="hero-grid"/><motion.div className="hero-orb" style={{scale:heroScale}}/><div className="hero-ring"/><Image className="hero-photo" src={profile} alt="" priority sizes="(max-width:900px) 78vw, 46vw"/><div className="hero-word"><span>SECURITY</span><span>CREATIVE</span></div><div className="hero-badge">Ethical Hacking</div><div className="hero-badge two">Cyber Security</div><div className="hero-signature">Gowtham Sai</div></div>
<motion.div className="hero-inner" style={{y:heroY}}><div className="hero-kicker">Hello, I&apos;m Gowtham · Software Engineer · Cybersecurity</div><div className="hero-copy"><h1>HACK<br/>LEARN<br/>BUILD<span style={{color:"var(--red)"}}>.</span></h1><p>Turning curiosity into secure, useful digital experiences through engineering and offensive security.</p></div><div className="hero-actions"><a className="button button-primary" href="#work">View my work <ArrowDown size={15}/></a><a className="button button-ghost" href="/contact">Let&apos;s talk <ArrowUpRight size={15}/></a></div><div className="hero-bottom"><div className="scroll-pill"><span/></div><span>Scroll down</span></div></motion.div>
<div className="hero-card"><h3>Building a safer digital world through engineering &amp; security.</h3><hr/><a className="hero-card-link" href="/contact">Let&apos;s connect <ArrowUpRight size={14}/></a><div className="availability-seal">Open<br/>to<br/>opportunities<br/>↗</div></div></section>
<div className="marquee"><div className="marquee-track">{["CYBER SECURITY","ETHICAL HACKING","SOFTWARE ENGINEERING","WEB APPLICATIONS","NETWORK SECURITY","CYBER SECURITY","ETHICAL HACKING","SOFTWARE ENGINEERING"].map((x,i)=><span key={i}>{x}<b>✦</b></span>)}</div></div>
<section className="section story"><div><span className="eyebrow">/ 01 — THE APPROACH</span></div><div className="story-copy"><p className="story-lead">I build where <span className="serif">security, engineering, and visual thinking</span> meet.</p><p className="story-body">My focus is creating software and interfaces that feel clear on the surface while the engineering underneath stays intentional, maintainable, and secure.</p></div></section>
<section id="work" className="section"><div className="section-head"><div><span className="eyebrow">/ 02 — SELECTED WORK</span><h2 className="section-title">Built with <span className="serif">intent.</span></h2></div><a className="button button-ghost" href="/work">View all projects <ArrowUpRight size={16}/></a></div><div className="work-grid">
<motion.a className="work-card large" href={projects[0].href} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.7}}><div className="work-media"><Image src={projects[0].image} alt={projects[0].title} fill sizes="(max-width:900px) 100vw, 60vw"/><div className="work-overlay"/><span className="work-pill">01 · {projects[0].category}</span><span className="work-arrow"><ArrowUpRight size={20}/></span></div><div className="work-caption"><div><h3>{projects[0].title}</h3><span className="eyebrow">{projects[0].year}</span></div><div><p>{projects[0].description}</p><div className="stack">{projects[0].stack.map(x=><span key={x}>{x}</span>)}</div></div></div></motion.a>
<motion.a className="work-card small" href={projects[1].href} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.7,delay:.08}}><div className="work-media"><Image src={projects[1].image} alt={projects[1].title} fill sizes="(max-width:900px) 100vw, 34vw"/><div className="work-overlay"/><span className="work-pill">02 · {projects[1].category}</span><span className="work-arrow"><ArrowUpRight size={20}/></span></div><div className="work-caption"><div><h3>{projects[1].title}</h3><span className="eyebrow">{projects[1].year}</span></div><div><p>{projects[1].description}</p></div></div></motion.a>
</div></section>
<section className="section"><div className="about-panel"><div className="about-image"><Image src={profile} alt="Gowtham" fill sizes="(max-width:900px) 100vw, 40vw"/></div><div className="about-copy"><span className="eyebrow" style={{color:"#ff745c"}}>/ 03 — ABOUT ME</span><h2>Software engineer with a <span className="serif">security mindset.</span></h2><p>I work across frontend engineering, web development, networking, and offensive-security practice — combining product thinking with hands-on technical work.</p><a className="button button-primary" href="/about">More about me <ArrowUpRight size={15}/></a><div className="stats"><div><strong>2000+</strong><span>Students trained</span></div><div><strong>20+</strong><span>Projects &amp; labs</span></div><div><strong>4+</strong><span>Security events</span></div></div></div></div></section>
<section className="section"><div className="work-grid"><a className="work-card small" href={projects[2].href}><div className="work-media"><Image src={projects[2].image} alt={projects[2].title} fill sizes="(max-width:900px) 100vw, 34vw"/><div className="work-overlay"/><span className="work-pill">03 · {projects[2].category}</span><span className="work-arrow"><ArrowUpRight size={20}/></span></div><div className="work-caption"><div><h3>{projects[2].title}</h3><span className="eyebrow">{projects[2].year}</span></div><p>{projects[2].description}</p></div></a><a className="work-card large" href={projects[3].href}><div className="work-media"><Image src={projects[3].image} alt={projects[3].title} fill sizes="(max-width:900px) 100vw, 60vw"/><div className="work-overlay"/><span className="work-pill">04 · {projects[3].category}</span><span className="work-arrow"><ArrowUpRight size={20}/></span></div><div className="work-caption"><div><h3>{projects[3].title}</h3><span className="eyebrow">{projects[3].year}</span></div><p>{projects[3].description}</p></div></a></div></section>
<section className="section"><div className="contact-band"><span className="eyebrow">/ 04 — CONTACT</span><Sparkles className="contact-star" size={120}/><h2>Have an idea?<br/><span className="serif">Let&apos;s build it.</span></h2><p>Open to software engineering roles, cybersecurity opportunities, collaborations, and interesting products.</p><a className="contact-link" href="/contact">Start a conversation <ArrowUpRight size={21}/></a></div></section>
<footer className="site-footer"><span>© 2026 GOWTHAM SATYA SAI</span><div><a href="https://github.com/gowthamsai117" target="_blank" rel="noreferrer"><Github size={13}/> GitHub</a><a href="https://www.linkedin.com/in/gowtham-satya-sai-m" target="_blank" rel="noreferrer"><Linkedin size={13}/> LinkedIn</a><a href="mailto:gowthamsatyasai123@gmail.com"><Mail size={13}/> Email</a></div></footer>
</main>}